# Generated by Django 5.2 on 2025-05-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonpackages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonpackage',
            name='paid_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lessonpackage',
            name='unpaid_hours',
            field=models.FloatField(default=0),
        ),
    ]
