# Generated by Django 5.2 on 2025-04-08 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_lessons', models.PositiveIntegerField(default=0, help_text='Total number of lessons in the program')),
                ('completed_lessons', models.PositiveIntegerField(default=0, help_text='Number of lessons completed by the student')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_progresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
