# Generated by Django 5.2 on 2025-05-04 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingprogress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingprogress',
            name='completed_lessons',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de leçons déjà complétées par l’élève', verbose_name='Leçons complétées'),
        ),
        migrations.AlterField(
            model_name='trainingprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='trainingprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_progresses', to=settings.AUTH_USER_MODEL, verbose_name='Élève'),
        ),
        migrations.AlterField(
            model_name='trainingprogress',
            name='total_lessons',
            field=models.PositiveIntegerField(default=0, help_text='Nombre total de leçons dans le programme', verbose_name='Nombre total de leçons'),
        ),
        migrations.AlterField(
            model_name='trainingprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
    ]
