# Generated by Django 5.2 on 2025-05-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointmentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Prévu'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('refused', 'Refusée'), ('proposed', 'Proposition de l’instructeur')], default='pending', max_length=20),
        ),
    ]
